.TH "frate" "1" "2023-11-05" "cmaker" "cmaker manual"
.SH "NAME"
\fBfrate - c/cpp package manager\fR
.SH SYNOPSIS
.P
\fBfrate <sub\-command>\fR
.SH DESCRIPTION
.P
\fBCmaker\fR came to fruition out of the desperate hopes and dreams of a few people looking to softly lighten their suffering while using c++\.
.SH init
.P
Initializes your project\. You'll be prompted with information to enter and frate will take care of the rest\.
.br
This will create a cmake file, 1 source file in src directory and config\.toml, where frate specific configuration is stored\.
.SS options
.SS \-y | \-\-skip\-init
.P
Skips initialization\.
.SS \-n | \-\-name example\-name
.P
Name of your project
.SS \-l | \-\-language cpp/c
.P
Language of your choice, c or cpp\.
.SH run
.P
Builds and runs your project\.
.SH watch
.P
Same a run command, but also watches file changes and rebuilds your project accordingly\.
.SH add
.P
This command adds a dependency, library or flag to your project\.
.br
\fBSubcommands:\fR
.SS dep
.P
Searches and adds dependency to your project\.
.br
Example:
.RS 2
.nf
frate add dep sdl
.fi
.RE
.P
You'll be shown found results and will be promted to choose from the list\.
.SS lib
.P
Searches and adds library to your project\.
.SS flags
.P
Adds flag to your project\.
.SH ftp
.P
Deletes the entire project :)\.
.br
Why?
.br
Why not?

